### ISSUE TITLE
enhancement: update communication status in DB 

### ISSUE THREAD

**Issue by PritamIT2023** [wrappid/service-core#2]
### Prerequisite: 
- Make wrappid service template application function registry available for Service Core
eg. setupModels or setupTasks

### Task

- [ ] Create a single communication history table
- [ ] Create below function(s) in communication module
  - [ ] Create entry in Communication History table
  - [ ] Update communication history row _status column with Retry Count column if needed.
- [ ] The function will be used in Service Core by the function registry 
- [ ]  The function will create a entry in table based on communication type , Also update entry status based on directFlag .
